FROM node:12.13.1-alpine
WORKDIR /home/node
COPY . /home/node

# Install Kompose
RUN apk add curl
RUN curl -L https://github.com/kubernetes/kompose/releases/download/v1.20.0/kompose-linux-amd64 -o kompose
RUN chmod +x kompose
RUN mv ./kompose /usr/local/bin/kompose

# Set environment varibles
ENV TZ America/Toronto
ENV NODE_ENV production

# Install dependecies 
RUN npm install --production
# CMD ["/bin/sh", "entrypoint.sh"]
CMD ["node", "app.js"]


